name: Deploy to heroku and cloud build

on:
  push:
    branches:
      - master
    paths:
      - "posts/**"
      - "index/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-post-smark"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      - name: Deploy cloud build
        run: curl -X POST -d '{}' "${{secrets.DEV_URL}}"
